import Vue from "vue";
import Badge from "~/components/Badge.vue";
import BaseAlert from "~/components/BaseAlert.vue";
import BaseButton from "~/components/BaseButton.vue";
import BaseCheckbox from "~/components/BaseCheckbox.vue";
import BaseInput from "~/components/BaseInput.vue";
import BasePagination from "~/components/BasePagination.vue";
import BaseProgress from "~/components/BaseProgress.vue";
import BaseRadio from "~/components/BaseRadio.vue";
import BaseSlider from "~/components/BaseSlider.vue";
import BaseSwitch from "~/components/BaseSwitch.vue";
import Card from "~/components/Card.vue";
import Icon from "~/components/Icon.vue";
import AppTopAd from "~/components/AppTopAd";
import AppHeader from "~/components/AppHeader";
import AppFooter from "~/components/AppFooter";
import AppSubheader from "~/components/AppSubheader";
// import VueAwesomeSwiper from "vue-awesome-swiper";

Vue.component("badge", Badge);
Vue.component("baseAlert", BaseAlert);
Vue.component("baseButton", BaseButton);
Vue.component("baseCheckbox", BaseCheckbox);
Vue.component("baseInput", BaseInput);
Vue.component("basePagination", BasePagination);
Vue.component("baseProgress", BaseProgress);
Vue.component("baseRadio", BaseRadio);
Vue.component("baseSlider", BaseSlider);
Vue.component("baseSwitch", BaseSwitch);
Vue.component("card", Card);
Vue.component("icon", Icon);
Vue.component("AppHeader", AppHeader);
Vue.component("AppFooter", AppFooter);
Vue.component("AppTopAd", AppTopAd);
Vue.component("AppSubheader", AppSubheader);
// Vue.component("VueAwesomeSwiper", VueAwesomeSwiper);
